### ISSUE TITLE
Error: Couldn't find preset "es2015" relative to directory 

### ISSUE THREAD

**Issue by Jaspur** [VinceG/vue-web-cam#6]
```
vagrant@homestead:~/code/foobar$ npm run dev

> @ dev /home/vagrant/code/foobar
> npm run development


> @ development /home/vagrant/code/foobar
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting                                                                 -
 ERROR  Failed to compile with 1 errors                                 12:51:55

 error  in ./node_modules/vue-web-cam/src/webcam.vue

Module build failed: Error: Couldn't find preset "es2015" relative to directory "/home/vagrant/code/foobar/node_modules/vue-web-cam"
    at /home/vagrant/code/foobar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/home/vagrant/code/foobar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/vagrant/code/foobar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/vagrant/code/foobar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/vagrant/code/foobar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/vagrant/code/foobar/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/vagrant/code/foobar/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/vagrant/code/foobar/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/vagrant/code/foobar/node_modules/babel-loader/lib/index.js:50:20)
    at /home/vagrant/code/foobar/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/home/vagrant/code/foobar/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

 @ ./node_modules/vue-web-cam/src/webcam.vue 4:21-343
 @ ./resources/assets/js/scripts/scripts.js
 @ multi ./resources/assets/js/scripts/scripts.js

      Asset     Size  Chunks                    Chunk Names
 /js/mbs.js  4.68 MB       0  [emitted]  [big]  /js/mbs
/js/scripts.js  3.25 MB       1  [emitted]  [big]  /js/scripts

ERROR in ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-web-cam/src/webcam.vue
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/home/vagrant/code/foobar/node_modules/vue-web-cam"
    at /home/vagrant/code/foobar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/home/vagrant/code/foobar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/vagrant/code/foobar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/vagrant/code/foobar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/vagrant/code/foobar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/vagrant/code/foobar/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/vagrant/code/foobar/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/vagrant/code/foobar/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/vagrant/code/foobar/node_modules/babel-loader/lib/index.js:50:20)
    at /home/vagrant/code/foobar/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/home/vagrant/code/foobar/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
 @ ./node_modules/vue-web-cam/src/webcam.vue 4:21-343
 @ ./resources/assets/js/scripts/scripts.js
 @ multi ./resources/assets/js/scripts/scripts.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-06-15T10_51_55_526Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-06-15T10_51_55_539Z-debug.log
```

**Comment by VinceG** [comment]
@Jaspur 

```
yarn add -D babel-preset-es2015 babel-preset-stage-2
```
